export const TODAY = '2026-09-16';
export const money = n => new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(Number(n)||0);
export const modules = [
 {id:'dashboard',name:'Dashboard & tasks',group:'Workspace',icon:'SquaresFour',description:'Work that needs a decision, with an owner and a clear next step.',fields:['title','reference','owner','due','status'],statuses:['Open','In progress','Resolved'],action:'Resolve task'},
 {id:'partners',name:'Partners & contacts',group:'Network',icon:'UsersThree',description:'Your suppliers, buyers and logistics partners.',fields:['name','type','contact','email','country','status'],statuses:['Active','Under review','Inactive'],action:'Activate partner'},
 {id:'products',name:'Products & master data',group:'Orders',icon:'Cube',description:'Product dimensions, packaging and commercial references.',fields:['name','sku','unit','weight','volume','origin','status'],statuses:['Active','Under review','Inactive'],action:'Validate product'},
 {id:'purchase',name:'Purchase orders',group:'Orders',icon:'ShoppingBag',description:'Supplier commitments and inbound quantities.',fields:['name','partner','product','quantity','allocated','required','status'],statuses:['Draft','Confirmed','Partially shipped','Delivered'],action:'Confirm order'},
 {id:'sales',name:'Sales orders',group:'Orders',icon:'ShoppingCart',description:'Buyer requirements and export delivery commitments.',fields:['name','partner','product','quantity','required','status'],statuses:['Draft','Confirmed','Ready','Delivered'],action:'Confirm order'},
 {id:'planning',name:'Shipment planning',group:'Freight',icon:'Path',description:'Allocate order quantities and prepare the movement.',fields:['name','reference','quantity','origin','destination','ready','status'],statuses:['Draft','Ready for booking','Allocated'],action:'Approve plan'},
 {id:'rfqs',name:'Freight RFQs',group:'Freight',icon:'ChatCircleDots',description:'Compare equivalent offers and preserve the award decision.',fields:['name','reference','origin','destination','due','status'],statuses:['Draft','Collecting offers','Under review','Awarded'],action:'Review offers'},
 {id:'rates',name:'Rates & contracts',group:'Freight',icon:'Tag',description:'Rate validity, inclusions, exclusions and source evidence.',fields:['name','partner','origin','destination','amount','destinationCharge','validUntil','status'],statuses:['Incomplete','Valid','Expired','Awarded'],action:'Review rate'},
 {id:'bookings',name:'Bookings',group:'Freight',icon:'CalendarCheck',description:'Requests and provider confirmations kept distinct.',fields:['name','reference','partner','origin','destination','etd','eta','status'],statuses:['Draft','Requested','Confirmed','Cancelled'],action:'Confirm booking'},
 {id:'shipments',name:'Shipment operations',group:'Freight',icon:'Boat',description:'Orders, containers and milestones in one shipment record.',fields:['name','reference','origin','destination','provider','quantity','eta','status'],statuses:['Planned','Confirmed','In transit','Delivered','Closed'],action:'Advance shipment'},
 {id:'tracking',name:'Tracking & exceptions',group:'Freight',icon:'MapPin',description:'Milestone events with source times and actionable exceptions.',fields:['title','reference','location','eventDate','source','owner','status'],statuses:['Expected','Confirmed','Exception','Resolved'],action:'Confirm event'},
 {id:'transport',name:'Transport & delivery',group:'Freight',icon:'Truck',description:'Pickup, inland movement, delivery and empty return.',fields:['name','reference','partner','pickup','delivery','appointment','status'],statuses:['Requested','Scheduled','Collected','Delivered'],action:'Advance delivery'},
 {id:'documents',name:'Documents',group:'Operations',icon:'Files',description:'Review shipment documents and keep version history.',fields:['name','reference','type','version','owner','status'],statuses:['Draft','Needs correction','Approved','Final'],action:'Approve document'},
 {id:'customs',name:'Customs coordination',group:'Operations',icon:'ShieldCheck',description:'Broker checklists, queries and clearance evidence.',fields:['name','reference','broker','declaration','duty','status'],statuses:['Documents pending','Submitted','Query','Released'],action:'Record release'},
 {id:'costs',name:'Costs & landed cost',group:'Finance',icon:'Calculator',description:'Reconcile the expected cost and allocate it to product units.',fields:['name','reference','category','amount','actual','allocation','status'],statuses:['Estimated','Confirmed','Reconciled'],action:'Reconcile cost'},
 {id:'invoices',name:'Invoices & reconciliation',group:'Finance',icon:'Receipt',description:'Check supplier invoices against agreed charges.',fields:['name','reference','partner','amount','expected','due','status'],statuses:['Under review','Disputed','Approved','Paid'],action:'Review invoice'},
 {id:'claims',name:'Insurance & claims',group:'Finance',icon:'Umbrella',description:'Evidence, deadlines and recovery progress.',fields:['name','reference','policy','amount','deadline','status'],statuses:['Draft','Submitted','In review','Settled'],action:'Advance claim'},
 {id:'portal',name:'Partner portal',group:'Network',icon:'Handshake',description:'Shared requests and confirmations from assigned partners.',fields:['title','reference','partner','due','status'],statuses:['Awaiting response','Received','Reviewed'],action:'Review response'},
 {id:'reports',name:'Reports & analytics',group:'Workspace',icon:'ChartBar',description:'Explain performance using the underlying records.',fields:['name','period','owner','status'],statuses:['Ready','Draft'],action:'Open report'},
 {id:'users',name:'User management',group:'Workspace',icon:'UsersThree',description:'Internal user accounts, access status and role assignment.',fields:['name','email','phone','role','status'],statuses:['Active','Inactive','Pending'],action:'Create user'},
 {id:'roles',name:'Roles & permissions',group:'Workspace',icon:'ShieldCheck',description:'Role master and granular action permissions matrix.',fields:['name','description','status'],statuses:['Active'],action:'Save permissions'},
 {id:'admin',name:'System settings',group:'Workspace',icon:'GearSix',description:'Central registry for statuses, dropdowns, defaults, org extensions and audit history.',fields:['name','type','value','status'],statuses:['Active','Not connected','Demo only'],action:'Review setting'},
 {id:'organization',name:'Organization',group:'Workspace',icon:'Buildings',description:'Tenant company profile, carrier verification and enterprise configuration.',fields:['legal_name','tax_id','dot_number','mc_number','status'],statuses:['Active','Under review'],action:'Edit profile'}
];
export const labels = {id:'Reference',name:'Name',title:'Task or event',reference:'Linked reference',partner:'Partner',product:'Product',quantity:'Quantity',allocated:'Allocated quantity',required:'Required by',due:'Due date',ready:'Cargo ready',amount:'Amount (USD)',actual:'Actual (USD)',expected:'Agreed (USD)',destinationCharge:'Destination charge (USD)',validUntil:'Valid until',etd:'Departure',eta:'Arrival',eventDate:'Event date',weight:'Weight (kg / unit)',volume:'Volume (m³ / unit)',unit:'Unit',sku:'SKU',duty:'Duty estimate (USD)',allocation:'Allocation method',policy:'Policy reference',deadline:'Claim deadline',pickup:'Pickup location',delivery:'Delivery location',appointment:'Appointment',contact:'Contact',email:'Email',phone:'Phone',role:'Assigned role',status:'Status',legal_name:'Legal Name',tax_id:'Tax ID',dot_number:'USDOT Number',mc_number:'MC Number'};
export const numeric = ['quantity','allocated','weight','volume','amount','actual','expected','destinationCharge','duty'];
export const dates = ['required','due','ready','validUntil','etd','eta','eventDate','deadline','appointment'];
export const initialRecords = {
 dashboard:[{id:'TASK-01',title:'Clarify destination handling',reference:'PO-1042',owner:'Ananya Rao',due:'2026-09-16',status:'Open'},{id:'TASK-02',title:'Correct packing list quantity',reference:'SO-558',owner:'Vikram Shah',due:'2026-09-17',status:'Open'},{id:'TASK-03',title:'Review unapproved surcharge',reference:'INV-091',owner:'Ananya Rao',due:'2026-09-18',status:'Open'}],
 partners:[{id:'PT-01',name:'OceanBridge Logistics',type:'Forwarder',contact:'Maya Chen',email:'maya@oceanbridge.example',country:'Singapore',status:'Active'},{id:'PT-02',name:'Shenzhen Components',type:'Supplier',contact:'Lin Wei',email:'lin@components.example',country:'China',status:'Active'},{id:'PT-03',name:'Bluewater Freight',type:'Forwarder',contact:'James Wilson',email:'james@bluewater.example',country:'India',status:'Active'},{id:'PT-04',name:'Nordic Industrial',type:'Buyer',contact:'Eva Larsen',email:'eva@nordic.example',country:'Germany',status:'Active'}],
 products:[{id:'PR-01',name:'Control unit CT-200',sku:'CT-200',unit:'units',weight:2.5,volume:0.012,origin:'China',status:'Active'},{id:'PR-02',name:'Precision valve PV-40',sku:'PV-40',unit:'units',weight:1.2,volume:0.008,origin:'India',status:'Active'}],
 purchase:[{id:'PO-1042',name:'September control units',partner:'Shenzhen Components',product:'CT-200',quantity:600,allocated:600,required:'2026-09-30',status:'Confirmed'},{id:'PO-1048',name:'October control units',partner:'Shenzhen Components',product:'CT-200',quantity:800,allocated:0,required:'2026-10-15',status:'Draft'}],
 sales:[{id:'SO-558',name:'Nordic valve replenishment',partner:'Nordic Industrial',product:'PV-40',quantity:400,required:'2026-10-08',status:'Confirmed'}],
 planning:[{id:'PLAN-204',name:'Shanghai import plan',reference:'PO-1042',quantity:600,origin:'Shanghai',destination:'Chennai',ready:'2026-09-18',status:'Draft'},{id:'PLAN-118',name:'Hamburg export plan',reference:'SO-558',quantity:400,origin:'Nhava Sheva',destination:'Hamburg',ready:'2026-09-20',status:'Draft'}],
 rfqs:[{id:'RFQ-032',name:'Shanghai to Chennai FCL',reference:'PO-1042',origin:'Shanghai',destination:'Chennai',due:'2026-09-17',status:'Under review'}],
 rates:[{id:'OB-082',name:'Ocean FCL via Singapore',partner:'OceanBridge Logistics',origin:'Shanghai',destination:'Chennai',amount:2840,destinationCharge:'',validUntil:'2026-09-20',status:'Incomplete'},{id:'BW-093',name:'Ocean FCL direct',partner:'Bluewater Freight',origin:'Shanghai',destination:'Chennai',amount:2680,destinationCharge:400,validUntil:'2026-09-22',status:'Valid'},{id:'EP-014',name:'Ocean FCL via Singapore',partner:'Eastport Logistics',origin:'Shanghai',destination:'Chennai',amount:2820,destinationCharge:440,validUntil:'2026-09-21',status:'Valid'}],
 bookings:[{id:'BK-118',name:'Nordic September export',reference:'SO-558',partner:'Bluewater Freight',origin:'Nhava Sheva',destination:'Hamburg',etd:'2026-09-22',eta:'2026-10-06',status:'Confirmed'}],
 shipments:[{id:'IMP-204',name:'Control units import',reference:'PO-1042',origin:'Shanghai',destination:'Chennai',provider:'Not awarded',quantity:600,eta:'2026-09-27',status:'Planned'},{id:'EXP-118',name:'Precision valves export',reference:'SO-558',origin:'Nhava Sheva',destination:'Hamburg',provider:'Bluewater Freight',quantity:400,eta:'2026-10-06',status:'Confirmed'},{id:'IMP-190',name:'August components',reference:'PO-1021',origin:'Singapore',destination:'Mumbai',provider:'OceanBridge Logistics',quantity:300,eta:'2026-09-12',status:'Delivered'}],
 tracking:[{id:'EV-204',title:'Cargo ready for pickup',reference:'IMP-204',location:'Shanghai',eventDate:'2026-09-18',source:'Supplier email',owner:'Ananya Rao',status:'Expected'},{id:'EV-118',title:'Export packing list mismatch',reference:'EXP-118',location:'Nhava Sheva',eventDate:'2026-09-16',source:'Document review',owner:'Vikram Shah',status:'Exception'}],
 transport:[{id:'TR-204',name:'Factory to Shanghai terminal',reference:'IMP-204',partner:'Eastern Road Logistics',pickup:'Shenzhen Components factory',delivery:'Shanghai terminal',appointment:'2026-09-19',status:'Requested'},{id:'TR-118',name:'Export container pickup',reference:'EXP-118',partner:'Chennai Roadways',pickup:'Meridian facility',delivery:'Nhava Sheva terminal',appointment:'2026-09-20',status:'Scheduled'}],
 documents:[{id:'DOC-01',name:'Order PO-1042',reference:'PO-1042',type:'Purchase order',version:1,owner:'Ananya Rao',status:'Approved',content:'PO-1042 · Shenzhen Components\n600 × CT-200 control units\nGoods value USD 24,000\nCargo ready 18 September 2026\nRequired Chennai 30 September 2026'}, {id:'DOC-02',name:'Supplier readiness email',reference:'PO-1042',type:'Email',version:1,owner:'Ananya Rao',status:'Approved',content:'16 September 2026\nFrom: Shenzhen Components (sample)\n600 control units will be ready on 18 September. Please confirm pickup.'},{id:'DOC-03',name:'Offer OB-082',reference:'RFQ-032',type:'Freight offer',version:1,owner:'Ananya Rao',status:'Needs correction',content:'OceanBridge Logistics · Illustrative offer\nOcean freight: USD 2,400\nOrigin charges: USD 440\nDestination handling: excluded / unconfirmed\nKnown charges: USD 2,840\nValid until 20 September 2026'},{id:'DOC-04',name:'Packing list EXP-118',reference:'SO-558',type:'Packing list',version:1,owner:'Vikram Shah',status:'Needs correction',content:'Packing list EXP-118 v1\nPrecision valves PV-40: 380 units\nSales order SO-558 requires 400 units.\nQuantity mismatch: 20 units.'},{id:'DOC-05',name:'Commercial invoice EXP-118',reference:'SO-558',type:'Commercial invoice',version:1,owner:'Vikram Shah',status:'Approved',content:'Commercial invoice · Sample\nNordic Industrial\n400 × PV-40 precision valves\nTotal goods value USD 18,000'}],
 customs:[{id:'CUS-118',name:'Export clearance EXP-118',reference:'EXP-118',broker:'Meridian Customs Partner',declaration:'Pending',duty:0,status:'Documents pending'}],
 costs:[{id:'COST-01',name:'Control units goods value',reference:'IMP-204',category:'Goods',amount:24000,actual:24000,allocation:'Quantity',status:'Confirmed'},{id:'COST-02',name:'Import ocean and origin charges',reference:'IMP-204',category:'Freight',amount:2840,actual:0,allocation:'Quantity',status:'Estimated'},{id:'COST-03',name:'Import insurance',reference:'IMP-204',category:'Insurance',amount:120,actual:120,allocation:'Quantity',status:'Confirmed'}],
 invoices:[{id:'INV-091',name:'August freight invoice',reference:'IMP-190',partner:'OceanBridge Logistics',amount:2640,expected:2400,due:'2026-09-25',status:'Under review'}],
 claims:[{id:'CLM-012',name:'Transit damage to 6 units',reference:'IMP-190',policy:'MAR-2026-041',amount:480,deadline:'2026-09-28',status:'Draft'}],
 portal:[{id:'REQ-204',title:'Confirm cargo readiness',reference:'PO-1042',partner:'Shenzhen Components',due:'2026-09-16',status:'Received'},{id:'REQ-032',title:'Confirm destination handling',reference:'RFQ-032',partner:'OceanBridge Logistics',due:'2026-09-17',status:'Awaiting response'}],
 reports:[{id:'RPT-01',name:'Shipment status and delivery',period:'September 2026',owner:'Logistics',status:'Ready'},{id:'RPT-02',name:'Cost variance and invoice review',period:'September 2026',owner:'Finance',status:'Ready'}],
 users:[],
 roles:[],
 organization:[],
 admin:[{id:'SET-01',name:'External action approval',type:'Policy',value:'Human review required',status:'Active'},{id:'SET-02',name:'Carrier connections',type:'Integration',value:'No carrier credentials configured',status:'Not connected'},{id:'SET-03',name:'Email account',type:'Integration',value:'No mailbox connected',status:'Not connected'},{id:'SET-04',name:'AI model',type:'Integration',value:'Scripted demonstration responses',status:'Demo only'}]
};
export const seedMissions=[{id:'import',name:'Shanghai import plan',title:'Import 600 control units to Chennai',reference:'PO-1042',subtitle:'PO-1042 · Chennai',goal:'Plan this import and compare the freight offers. Ask me before sending or booking.',type:'import'},{id:'export',name:'September exports',title:'Prepare 400 precision valves for export',reference:'SO-558',subtitle:'SO-558 · Hamburg',goal:'Check our export documents and prepare this shipment for the buyer.',type:'export'},{id:'invoice',name:'Freight invoice review',title:'Review the freight invoice for IMP-190',reference:'INV-091',subtitle:'INV-091 · Finance',goal:'Check this invoice against the agreed rate and draft a clarification for any unexpected costs.',type:'invoice'}];

export const seedSettingCategories=[
 {id:'cat-shipment-status',module:'shipment',key:'shipment.status',name:'Shipment Status',description:'Core shipment lifecycle values shared by operations and reporting.',isSystemDefined:true,values:[
  {id:'set-draft',value:'draft',label:'Draft',sortOrder:1,isActive:true,isDefault:true,isSystemDefined:true},
  {id:'set-quoted',value:'quoted',label:'Quoted',sortOrder:2,isActive:true,isDefault:false,isSystemDefined:true},
  {id:'set-booked',value:'booked',label:'Booked',sortOrder:3,isActive:true,isDefault:false,isSystemDefined:true},
  {id:'set-transit',value:'in_transit',label:'In Transit',sortOrder:4,isActive:true,isDefault:false,isSystemDefined:true},
  {id:'set-delivered',value:'delivered',label:'Delivered',sortOrder:5,isActive:true,isDefault:false,isSystemDefined:true},
  {id:'set-closed',value:'closed',label:'Closed / Invoiced',sortOrder:6,isActive:true,isDefault:false,isSystemDefined:true}
 ]},
 {id:'cat-equipment-type',module:'equipment',key:'equipment.type',name:'Equipment Type',description:'Equipment options used by shipment planning and load board filters.',isSystemDefined:true,values:[
  {id:'set-dry',value:'dry_van',label:'Dry van',sortOrder:1,isActive:true,isDefault:true,isSystemDefined:true},
  {id:'set-reefer',value:'reefer',label:'Reefer',sortOrder:2,isActive:true,isDefault:false,isSystemDefined:true},
  {id:'set-flatbed',value:'flatbed',label:'Flatbed',sortOrder:3,isActive:true,isDefault:false,isSystemDefined:false}
 ]},
 {id:'cat-accessorial-type',module:'quoting',key:'accessorial.type',name:'Accessorial Type',description:'Optional charges available to quoting teams and organization extensions.',isSystemDefined:false,values:[
  {id:'set-storage',value:'storage',label:'Storage',sortOrder:1,isActive:true,isDefault:false,isSystemDefined:true},
  {id:'set-detention',value:'detention',label:'Detention',sortOrder:2,isActive:true,isDefault:true,isSystemDefined:false},
  {id:'set-inspection',value:'inspection',label:'Inspection',sortOrder:3,isActive:false,isDefault:false,isSystemDefined:false}
 ],overrides:[{id:'org-reefer',orgId:'Meridian Trading',value:'reefer_monitoring',label:'Reefer monitoring',sortOrder:4,isActive:true}]}
];
